# api/config/packages/api_platform.yaml https://api-platform.com/docs/core/configuration/
api_platform:
  title: Hello API Platform
  version: 1.0.0
  defaults:
    #    stateless: true
    cache_headers:
      vary: [ 'Content-Type', 'Authorization', 'Origin' ]
    # To enable or disable pagination for all resource collections.
    pagination_enabled: true
    # To allow the client to enable or disable the pagination.
    pagination_client_enabled: true
    # To allow the client to set the number of items per page.
    pagination_client_items_per_page: true
    # To allow the client to enable or disable the partial pagination.
    pagination_client_partial: true
    # The default number of items per page.
    pagination_items_per_page: 10
    # The maximum number of items per page.
    pagination_maximum_items_per_page: 200
    # To allow partial pagination for all resource collections.
    # This improves performances by skipping the `COUNT` query.
    pagination_partial: true
    normalization_context:
      skip_null_values: false
    collectDenormalizationErrors: true
  mapping:
    paths:
      - '%kernel.project_dir%/src/Domain/Entity'
      - '%kernel.project_dir%/src/Application/DTO'
  swagger:
    versions: [ 3 ]
    api_keys:
      JWT:
        name: Authorization
        type: header