# config/packages/lexik_jwt_authentication.yaml
lexik_jwt_authentication:
  secret_key: '%env(resolve:JWT_SECRET_KEY)%' # required for token creation
  public_key: '%env(resolve:JWT_PUBLIC_KEY)%' # required for token verification
  pass_phrase: '%env(JWT_PASSPHRASE)%' # required for token creation
  token_ttl: '%env(int:JWT_TOKEN_TTL)%' # in seconds, default is 3600
  api_platform:
    check_path: /api/role-model-bundle/users/login
    username_path: username
    password_path: password