<?php

declare(strict_types=1);

namespace Slcorp\RoleModelBundle\Infrastructure\Persistence\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250314064908 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE role_model_bundle_operations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, comment VARCHAR(255) NOT NULL, lft INT NOT NULL, lvl INT NOT NULL, rgt INT NOT NULL, description VARCHAR(255) DEFAULT NULL, delete BOOLEAN DEFAULT false NOT NULL, time_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, time_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, root INT DEFAULT NULL, parent INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B4BE5C6477153098 ON role_model_bundle_operations (code)');
        $this->addSql('CREATE INDEX IDX_B4BE5C6416F4F95B ON role_model_bundle_operations (root)');
        $this->addSql('CREATE INDEX IDX_B4BE5C643D8E604F ON role_model_bundle_operations (parent)');
        $this->addSql('CREATE TABLE role_model_bundle_refresh_tokens (refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D7453B56C74F2195 ON role_model_bundle_refresh_tokens (refresh_token)');
        $this->addSql('CREATE TABLE role_model_bundle_roles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(255) DEFAULT NULL, delete BOOLEAN DEFAULT false NOT NULL, time_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, time_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A9F6314C5E237E06 ON role_model_bundle_roles (name)');
        $this->addSql('CREATE TABLE role_model_bundle_role_operations (role_id INT NOT NULL, operation_id INT NOT NULL, PRIMARY KEY(role_id, operation_id))');
        $this->addSql('CREATE INDEX IDX_F269F697D60322AC ON role_model_bundle_role_operations (role_id)');
        $this->addSql('CREATE INDEX IDX_F269F69744AC3583 ON role_model_bundle_role_operations (operation_id)');
        $this->addSql('CREATE TABLE role_model_bundle_user_emails (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, time_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, time_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1B973583E7927C74 ON role_model_bundle_user_emails (email)');
        $this->addSql('CREATE INDEX IDX_1B973583A76ED395 ON role_model_bundle_user_emails (user_id)');
        $this->addSql('CREATE TABLE role_model_bundle_users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(255) NOT NULL, active BOOLEAN DEFAULT true NOT NULL, password VARCHAR(255) DEFAULT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, patronymic VARCHAR(255) DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, country VARCHAR(2) DEFAULT NULL, region VARCHAR(255) DEFAULT NULL, city VARCHAR(120) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, ad_login VARCHAR(100) DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, gid VARCHAR(256) DEFAULT NULL, delete BOOLEAN DEFAULT false NOT NULL, time_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, time_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B4BBA62F85E0677 ON role_model_bundle_users (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B4BBA6297689195 ON role_model_bundle_users (ad_login)');
        $this->addSql('CREATE TABLE role_model_bundle_user_roles (user_id INT NOT NULL, role_id INT NOT NULL, PRIMARY KEY(user_id, role_id))');
        $this->addSql('CREATE INDEX IDX_C856DAB3A76ED395 ON role_model_bundle_user_roles (user_id)');
        $this->addSql('CREATE INDEX IDX_C856DAB3D60322AC ON role_model_bundle_user_roles (role_id)');
        $this->addSql('ALTER TABLE role_model_bundle_operations ADD CONSTRAINT FK_B4BE5C6416F4F95B FOREIGN KEY (root) REFERENCES role_model_bundle_operations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_model_bundle_operations ADD CONSTRAINT FK_B4BE5C643D8E604F FOREIGN KEY (parent) REFERENCES role_model_bundle_operations (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_model_bundle_role_operations ADD CONSTRAINT FK_F269F697D60322AC FOREIGN KEY (role_id) REFERENCES role_model_bundle_roles (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_model_bundle_role_operations ADD CONSTRAINT FK_F269F69744AC3583 FOREIGN KEY (operation_id) REFERENCES role_model_bundle_operations (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_model_bundle_user_emails ADD CONSTRAINT FK_1B973583A76ED395 FOREIGN KEY (user_id) REFERENCES role_model_bundle_users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_model_bundle_user_roles ADD CONSTRAINT FK_C856DAB3A76ED395 FOREIGN KEY (user_id) REFERENCES role_model_bundle_users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_model_bundle_user_roles ADD CONSTRAINT FK_C856DAB3D60322AC FOREIGN KEY (role_id) REFERENCES role_model_bundle_roles (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE role_model_bundle_operations DROP CONSTRAINT FK_B4BE5C6416F4F95B');
        $this->addSql('ALTER TABLE role_model_bundle_operations DROP CONSTRAINT FK_B4BE5C643D8E604F');
        $this->addSql('ALTER TABLE role_model_bundle_role_operations DROP CONSTRAINT FK_F269F697D60322AC');
        $this->addSql('ALTER TABLE role_model_bundle_role_operations DROP CONSTRAINT FK_F269F69744AC3583');
        $this->addSql('ALTER TABLE role_model_bundle_user_emails DROP CONSTRAINT FK_1B973583A76ED395');
        $this->addSql('ALTER TABLE role_model_bundle_user_roles DROP CONSTRAINT FK_C856DAB3A76ED395');
        $this->addSql('ALTER TABLE role_model_bundle_user_roles DROP CONSTRAINT FK_C856DAB3D60322AC');
        $this->addSql('DROP TABLE role_model_bundle_operations');
        $this->addSql('DROP TABLE role_model_bundle_refresh_tokens');
        $this->addSql('DROP TABLE role_model_bundle_roles');
        $this->addSql('DROP TABLE role_model_bundle_role_operations');
        $this->addSql('DROP TABLE role_model_bundle_user_emails');
        $this->addSql('DROP TABLE role_model_bundle_users');
        $this->addSql('DROP TABLE role_model_bundle_user_roles');
    }
}
